requirements.txt, telebot/modules/memes.py
Reverts ksdfg/neko-chan-telebot#8
=> Revert "Deepfry"

telebot/__main__.py, telebot/modules/filter.py, telebot/modules/memes.py, telebot/modules/mute.py, telebot/modules/nhentai.py, telebot/modules/notes.py
Fix all the errors that were caused by me not knowing how to use markdown
=> Markdown fix

telebot/modules/admin.py
Admin actions to take in the chat
=> Admin actions

telebot/__main__.py, telebot/modules/__init__.py, telebot/modules/basics.py
shift basic commands out of __main__.py and add info command
=> Basics shift

telebot/modules/chat_actions.py
Add pin and purge as common chat actions
=> Chat actions

README.md
cuz I can't get it to work any other way ;_;
Signed-off-by: ksdfg <ksdfg123@gmail.com>
=> specify what value to give for LOAD and NO_LOAD

telebot/modules/ud.py
- bump up deps
- add urban dictionary module
=> urban dictionary

telebot/modules/admin.py
Add command to demote admins in admin module
=> Demote command

telebot/functions.py, telebot/modules/admin.py, telebot/modules/basics.py
Abstract the snippet of code which was used to fetch target user from quoted message or username given in message text to avoid same code snippet being repeated in multiple functions
=> Abstraction of Target User Retrieval from quoted message or username in message

telebot/modules/ud.py
- Use Markup Buttons instead of links in the UD results
- Randomize result
=> Urban Dictionary redux

requirements.txt, telebot/modules/admin.py, telebot/modules/basics.py, telebot/modules/db/exceptions.py, telebot/modules/exceptions.py, telebot/modules/filter.py, telebot/modules/memes.py, telebot/modules/nhentai.py, telebot/modules/notes.py, telebot/modules/quote.py, telebot/modules/stickers.py
- bump up ptb dependency
- use the run_async parameter of Handler instead of decorator in basics.py
- use the run_async parameter of Handler instead of decorator in admin.py
- use the run_async parameter of Handler instead of decorator in exceptions.py
- use the run_async parameter of Handler instead of decorator in filter.py
- use the run_async parameter of Handler instead of decorator in memes.py
- use the run_async parameter of Handler instead of decorator in nhentai.py
- use the run_async parameter of Handler instead of decorator in notes.py
- use the run_async parameter of Handler instead of decorator in quote.py
- use the run_async parameter of Handler instead of decorator in stickers.py
- fix mute, unmute and ban/kick
- fix exceptions module reply messages
- update exceptions …
=> Update PTB version and other minor changes

telebot/modules/memes.py
- add ability to stretch text by giving the text directly in the message
- add ability to owo-fy text by giving the text directly in the message
- add ability to zalgofy text by giving the text directly in the message
- add ability to mock text by giving the text directly in the message
=> Let commands in the memes module take input from the message itself

telebot/modules/admin.py
check if user being banned or kicked is a member of the group, reply with error message if they aren't.
=> Check if user is a member of given group for ban/kick

telebot/modules/admin.py
also send message before kicking/banning user, so the user can see the message and cry.
=> admin: ignore all arguments for /kick

poetry.lock, pyproject.toml, telebot/modules/nhentai.py
This seems useful instead of scraping on our own, the repo seems to be maintained as of now, and it will allow me to expand the functionality of this module in future
=> nhentai.py: use `hentai` lib to fetch doujin details

poetry.lock
Signed-off-by: ksdfg <ksdfg123@gmail.com>
=> bump: update dependencies

telebot/modules/regex.py
Signed-off-by: ksdfg <ksdfg123@gmail.com>
=> regex: fix arguments passed to reply message for audio, voice and video

poetry.lock, pyproject.toml, telebot/modules/basics.py, telebot/modules/nhentai.py
<a name="45f44c0"></a>
> 2021-11-17
* **basic:** use join to form spam string
* **nhentai:** send telegraph article for instant view as well as link to nhentai
=> Add instant view to sauce responses

poetry.lock, pyproject.toml
Reverts ksdfg/neko-chan-telebot#62
=> Revert "bump: update dependencies"

.github/workflows/workflow.yml, poetry.lock, pyproject.toml, telebot/modules/admin.py, telebot/modules/db/mute.py, telebot/modules/filter.py, telebot/modules/notes.py, telebot/modules/stickers.py, telebot/utils.py
- Revert "Merge pull request #63 from ksdfg/revert-62-deps_update"
- Update dependencies to the latest versions
- telebot/utils: switch from collections.Callable -> typing.Callable
- refactor(treewide): make use of the new match statements
- chore(workflow): update for py310
=> Python 3.10 migration

README.md, telebot/__init__.py, telebot/__main__.py, telebot/modules/__init__.py, telebot/modules/admin.py, telebot/modules/basics.py, telebot/modules/delete.py, telebot/modules/exceptions.py, telebot/modules/filter.py, telebot/modules/memes.py, telebot/modules/nhentai.py, telebot/modules/notes.py, telebot/modules/quote.py, telebot/modules/regex.py, telebot/modules/stickers.py, telebot/modules/ud.py, telebot/utils.py
Class objects can now be reused for both command previews as well as help texts, centralising the process.
=> Use class for storing commands descriptions

telebot/modules/admin.py
- fix(admin): replace usage of deprecated function
- chore(Admin): use local var to remove pycharm warning
=> fix ban kick

telebot/modules/db/users.py
Also some smol cleanups to user DB functions
Signed-off-by: Akhil Narang <me@akhilnarang.dev>
=> feat(users): update username in DB if its changed
